"""add nilai table for IPK calculator

Revision ID: 3c0b4653399f
Revises: 412f7bacf44d
Create Date: 2026-09-06 09:24:15.140670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c0b4653399f'
down_revision: Union[str, None] = '412f7bacf44d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nilai',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('mata_kuliah', sa.String(length=255), nullable=False),
    sa.Column('sks', sa.Integer(), nullable=False),
    sa.Column('nilai', sa.Float(), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nilai_semester'), 'nilai', ['semester'], unique=False)
    op.create_index(op.f('ix_nilai_user_id'), 'nilai', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_nilai_user_id'), table_name='nilai')
    op.drop_index(op.f('ix_nilai_semester'), table_name='nilai')
    op.drop_table('nilai')
    # ### end Alembic commands ###
